---
title: "Publications"
output: html_document
---
<br>


### Peer reviewed publications


* **[Multi-scale characterization of symbiont diversity in the pea aphid complex through metagenomic approaches.](https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-018-0562-9) <br>**
  **C. Guyomar**, F. Legeai, E. Jousselin, C. Mougel, C. Lemaitre and JC. Simon  <br>
  Microbiome, 2018
  
* **[Phylogenetic distribution, biogeography and the effects of land management upon bacterial non-specific acid phosphatase gene diversity and abundance.](https://link.springer.com/article/10.1007/s11104-017-3301-2)  <br>**
  A. Neal Andrew, M. Blackwell, E. Akkari, **C. Guyomar**, I. Clark, P. Hirsch, 2017.  <br>
  Plant and Soil 2017
  
* **[Land-use influences phosphatase gene microdiversity in soils.](https://onlinelibrary.wiley.com/doi/full/10.1111/1462-2920.13778) <br>**
  A. Neal Andrew, M. Rossmann, C. Brearley, E. Akkari, **C. Guyomar**, I. Clark, E. Allen, P. Hirsch, 2017.  <br>
  Environmental Microbiology 2017
  
  
### Pre-prints

* **[MinYS: Mine Your Symbiont by targeted genome assembly in symbiotic communities](https://www.biorxiv.org/content/10.1101/2019.12.13.875021v1) <br>**
   **C. Guyomar**, W. Delage, F. Legeai, C. Mougel, JC. Simon and C. Lemaitre

 

### Oral communications

* **Journées SeqBIM**, Marne-la-Vallée, 12/2019 <br>
MinYS: Mine Your Symbiont by targeted genome assembly in symbiotic communities.

* **JOBIM**, Nantes, 07/2019 <br>
MinYS: Mine Your Symbiont by targeted genome assembly in symbiotic communities.

* **International conference on holobionts**, Paris, 20/04/2017 <br>
Multi-scale characterization of symbiont diversity in the pea aphid complex through metagenomic approaches
  
* **Insect symbioaia workshop**, Sde Boker, Israel, 05/2017 <br>
Multi-scale characterization of symbiont diversity in the pea aphid complex through metagenomic approaches
  
* **Journées BioGenOuest**, Rennes, 14/12/2016
Aphid microbiota, from field ecology to metagenomics <br>


### Posters

* **C. Guyomar**, W. Delage, F. Legeai, C. Mougel, JC. Simon, C. Lemaitre. : [**Reference guided genome assembly in metagenomic samples**](documents/RECOMB_2018.pdf) ; RECOMB 2018, Paris

* **C. Guyomar**, F. Legeai, C. Lemaitre, JC. Simon. : [**Multi-scale characterization of symbiont diversity in the pea aphid complex through metagenomic approaches**](documents/JOBIM_2017.pdf), JOBIM 2017, Lille



